### ISSUE TITLE
Does the enablePurge option work?

### ISSUE THREAD

**Issue by contiki9** [Poimen/stencil-tailwind-plugin#10]
I'm using this plugin with `enablePurge` set to 'false'.
I thought that if I set it to 'false', 'purgecss' would not work and the tailwind CSS would not be removed.
However, in fact, the unused CSS was removed.

Was this the correct behavior?
I apologize if I am using it incorrectly.

```
export const config: config = {
  plugins: [tailwind({ enablePurge: false })],
};
```

I have created a repository to check the behavior of this configuration.
The 'text-blue-500' provided by tailwind has been removed.
![](https://gyazo.com/134387438014ece128e6b110e87922a8.png)

I hope it will be useful for your investigation.

https://github.com/contiki9/stencil-test-tailwind

Thank you for creating a nice plugin.

**Comment by Poimen** [comment]
> Was this the correct behavior?

Simple answer is yes...

The longer answer is that this is targeted at the JIT version of tailwind. The TW css would be quite large to include in web components - i.e. if you used shadow dom components, each component would contain _all_ the styles even those not used. Hence the footprint for the web component would be quite heavy. So the idea is that the web component would only contain the necessary styles and strip the rest not to create unnecessary load on the bundling/download. By targeting the JIT version of TW, it also allows for future mod's based on JIT syntax to keep the weight down.

So, essentially the idea is that the web component should be as light as possible when including all the utility classes. In essence, utility classes for web components are overkill in terms of their weight as there is no sharing in the shadow dom.

So the idea is to try to keep the css from bloating.


In terms of your repo, thanks :+1:  and, as a mild suggestion, you could enforce the prop:
```ts
@Prop() color: string = 'text-red-500';
```

HTH

**Comment by Poimen** [comment]
Ok, ignore that suggestion 🙈  Brain missing in action this afternoon...

**Comment by contiki9** [comment]
@Poimen 

Thank you for your answer.

I think your design using JIT mode is better one.
I will try to approach it in a different way.
