### ISSUE TITLE
Error: Cannot find module 'typescript' Require stack: -

### ISSUE THREAD

**Issue by jsbaguette** [Poimen/stencil-tailwind-plugin#14]
Hello using your plugin with the latest stencil core version. 2.12.1

Adding your plugin and here my stencil config:

<img width="1220" alt="Screen Shot 2022-01-19 at 3 37 06 PM" src="https://user-images.githubusercontent.com/11556276/150209729-d148560f-2937-4407-9be8-2067cad157b7.png">

but got this error when running npm start after:

<img width="1364" alt="Screen Shot 2022-01-19 at 3 37 26 PM" src="https://user-images.githubusercontent.com/11556276/150209763-b9dbe3be-eea9-4937-b692-61cdc6633f97.png">

Do you have any idea ?

thank you a lot for your work

**Comment by Poimen** [comment]
The plugin requires typescript to be installed as a dev dependency in your project.

Can you please check if your `package.json` has this?

**Comment by jsbaguette** [comment]
That looks it was the issue. Now having

<img width="1774" alt="Screen Shot 2022-01-20 at 1 42 18 AM" src="https://user-images.githubusercontent.com/11556276/150287043-f0211f26-0948-4fdd-b5ea-7b519cc71ca2.png">


<img width="1165" alt="Screen Shot 2022-01-20 at 1 42 47 AM" src="https://user-images.githubusercontent.com/11556276/150287096-4386133e-7f05-47b0-8c10-559c6e5d2dc4.png">

I am using your example in the doc with the bare minimum.  and here my tailwind
<img width="890" alt="Screen Shot 2022-01-20 at 1 43 10 AM" src="https://user-images.githubusercontent.com/11556276/150287151-049111ac-d1d7-4e4c-8606-921c413302b6.png">

**Comment by jsbaguette** [comment]
ok added manually via tailwindConf made it works apparently. I don't know if its the default behavior. But maybe in the doc we should say when somehting is required or not

**Comment by Poimen** [comment]
Glad it is working.

The plugin doesn't auto detect the config so you have to give it. 

I'll look at updating the docs to make it more explicit. Thanks for the feedback 🙂
