### ISSUE TITLE
Is there a way to prevent duplicate body style?

### ISSUE THREAD

**Issue by dtaalbers** [Poimen/stencil-tailwind-plugin#27]
Hi, me again 🙄 .

I have worked on this for a few days but can't get it fixed. Not entirely sure if this is related to your plugin though. But basically when I open the Developer tools everything things become slow. Also I have the feeling that the same issues causes the browser to be slow, but can't say that for sure yet. 

I am quite certain I know the problem for the slow Developer Tools though. Let me paint the picture (I added some new commits to my [example project](https://github.com/dtaalbers/tailwindcss-stenciljs-example), so you can follow along whilst I paint this picture. I have the following DOM structure:

```
index.html
    <my-page></my-page>
       <my-component></my-component>
       <my-second-component></my-second-component>
      
```
I count four custom components that are used. The problem I am having is when I open the Developer Tools I get the styling reference for the `body` four times. See screenshot:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6512556/192848757-d14aba9b-ddd3-4948-8d23-203ec8d00d38.png">

When you remove a component from the DOM structure, for example `<my-third-component></my-third-component>` which makes it three custom components in the DOM, the `body` styling also drops to three references.

Now, imagine a component library of 40-50 components and an application which consumes said component library. The application has some pretty complex pages which use a ton of those custom UX components from the library. From a single navigation component to tens of custom input components. You can imagine that the Developer Tools gets a ton of duplicate styling references to the DOM elements like in the simple example I gave earlier. I also suspect it slows down the performance of my application while using it, but can't say that for sure.

> This is because the same configuration is applied per component, so each component generates the same safelist. With Web Components in the shadow DOM, the idea is that they are self contained with all their CSS without leaking (or as little as possible). Hence, the "pass in the config and capture the CSS per component" works.

Quote from [here](https://github.com/Poimen/stencil-tailwind-plugin/issues/23). So reading that, I understand  that Stencil JS generates this for each of the used components in the DOM? Hence the amount of references?

Is there a way to prevent those extra references? Because in combination with the generated TW CSS and the amount of components I have/use, it's becoming a performance nightmare to be honest. See the short video. This is filtered on one particular class for one specific element. This is not even the biggest list of references I had one a single element.

https://user-images.githubusercontent.com/6512556/192853977-f9c5ec82-fad6-4f5f-9848-c9e13d7eefb1.mov

 If you think it has nothing to do with your plugin just let me know, I'll move the issue to the Stencil JS repository. Thanks anyway!

**Comment by Poimen** [comment]
If I recall, if the preflight is turned off, then transitions stopped working, so decided that it was safer having a little more output and not breaking random things

**Comment by dtaalbers** [comment]
>This is one of the downsides of TW with web components, TW doesn't target web components directly so things that would work for a page setting don't work well for web components, unfortunately.

Yeah, I was afraid of that. So it's nothing related to your plugin so might as well close the issue.

>If I recall, if the preflight is turned off, then transitions stopped working, so decided that it was safer having a little more output and not breaking random things

Yeah, I messed around a bit with preflight. But disabling it messed a lot of existing styling on my components.

>So what you're seeing is the impact of not scoping or using the shadow DOM. Web Components encapsulate all their own JS and CSS, but when not used with the scope or shadow, they are put into the global page space. Hence, this is what you are seeing.

What's your experience with this? Do you use scoped/shadow? You don't have the having the issues I am having?

**Comment by Poimen** [comment]
We use all shadow DOM components so all the styles are self contained. We use a lot of slots to compose components and layouts. With the shadow DOM we don't have these problems, but they are a little hidden. We also have a custom postcss plugin that cuts down the amount of unwanted selectors. 

I'm thinking that the new functional route for configuration could have some benefits to being able to drop selectors per file. Previously stated away from that because it was a big brush that couldn't be controlled, now the functional version gives much more control.

**Comment by alejandro25262** [comment]
@Poimen Could you tell me what plugins you use?

**Comment by Poimen** [comment]
Hey @alejandro25262 

In terms of TW - vanilla TW styles, we've got our own DS with tokens generated off Figma. 

In terms of Stencil - Tailwind+HMR (shameless plug 😄 ), sass (have a few mixins that have some legacy stuff), autoprefixer, postcss (custom "tree-shaking" thingy)

We don't have a lot of plugins - a lot of our stuff in built in scripts around for various build activities
