### ISSUE TITLE
wrong order of inline <style> breaks tailwind breakpoints

### ISSUE THREAD

**Issue by mschiele** [Poimen/stencil-tailwind-plugin#33]
Hi there,

first thanks a lot for your plugin - it work's really great! 

But I am facing issues with a tailwind breakpoint "flex flex-col md:flex-row" that get's applied, but does not take effect due to the wrong order of css styles... I have a root component that is using shadow=true. The root component uses other components, which may also use other components. The only component I tagged with shadow=true is the root component. I do this, because the subcomponents always get mounted into the root, so I don't need a shadow dom for those anymore. Shadow would duplicate my styles a lot, e.g. I am rendering a list of components, that would each repeat my styles when using shadow -> would blow up my dom a lot.

So there is some workarounds I found that this issue does not happen, e.g.:
- put all code into one component
- activate shadow for each component (as you did in your example)

The thing is I plan to use this plugin for a lot of more components, some of them need shadow as they are getting used as root components, other components don't need it as I simply use them in other components. I can't use functional components as they require a state.

Is there any configuration option, I can use to control the order of the styles generated or tell the plugin to put all css of non shadow components into one <style></style> directive?

Thanks a lot for you help

**Comment by Poimen** [comment]
Glad the library is working well for you.

I take it you came to a solution?
