### ISSUE TITLE
Add way to include Autoprefixer plugin

### ISSUE THREAD

**Issue by bradlc** [Poimen/stencil-tailwind-plugin#4]
Original issue: https://github.com/tailwindlabs/tailwindcss/issues/5296

As far as I can tell there's currently no way to run the Tailwind output through additional PostCSS plugins, but some classes need vendor prefixes to work in certain browsers, e.g. `bg-clip-text`

It would be nice if you could specify additional PostCSS plugins. Alternatively, Autoprefixer could be added by default, similar to how `postcss-import` and `cssnano` are already.

**Comment by Poimen** [comment]
I have been having some fun with `postcss` and passing the output to further `postcss` plugins in the chaining of stencil. I was wanting to try an attempt to pass the tw classes to be triggered further down the line, but I have seen some funky behaviour with things like `cssnano` and `@apply` rules - as in `cssnano` delete's the `@apply` rules and bundles all the rules into a single rule, even though `@apply` is different across all the rules.

I'll have a look into this shortly

**Comment by Poimen** [comment]
autoprefixer should now be applied as expected with default configuration.

I have also added the ability to override the complete postcss config if required. 

The stencil pipeline is requiring more understanding to try to pass tailwind styles over to it.

**Comment by Zegoverno** [comment]
I would like to experiment adding a tailwind plugin... I tried to follow the steps below and pass this new tailwind.config.js like in this example:

 tailwind({
      tailwindConf: tailwindConfig
    }),

Install  DaisyUI as Tailwind CSS plugin
(You need Node.js and Tailwind CSS installed.)
1. Install DaisyUI:
npm i daisyui
2. Then add DaisyUI to your tailwind.config.js
module.exports = {
    plugins: [
      require('daisyui'),
    ],
  }

I couldn't get this working, any thoughts on how to do that? Many thanks
